### ISSUE TITLE
Indexing of Most Popular

### ISSUE THREAD

**Issue by danielpetty** [freejoe76/blockit#1]
Probably only marginally related to this, but I wanted us to find a way so that Google does not index the feed of "most popular" stories because it creates havoc with SEO, and very often, Google indexes something like this:

http://www.denverpost.com/popular/ci_27035525?source=most_viewed

Instead of this:

http://www.denverpost.com/avalanche/ci_27035525/slap-shots-thing-past-nhl

Requesting to see if possible to remove the "popular" section anchor from something Google indexes.

**Comment by freejoe76** [comment]
Hey, just noticed this, not sure how this issue ended up in this repo but if you could file it against https://github.com/dfmedia/popular
